### PR TITLE
add exposed pad version of TSSOP-20

### PR DESCRIPTION
**Pull request by descampsa**
Copied from TSSOP version, pad dimension comes from Allegro A4963 datasheet.

### CODE REVIEW

**Comment by jkriege2** [comment]
Hi!

thanks for the contribution. There are two things that would be great if you could still change:
1. Could you give the exposed pad the number 21, so it can be referenced by pins in the symbol?
2. I think there are usually vias in the EP ... like e.g. in the TSSOP-16_1EP or the HTSSOP-28_..._THermalPad ... could you add them? For that the pad is actually made up of an array of THT pins with only  tiny holes and rectangular copper that overlaps so the whole area is filled ...
3. According to the KLC the Courtyard should be 0.25mm offset from the pads and also from the enclosing silcscreen lines ... so as you're at it: could you move that courtyard a bit farther out to accomodate that? I know it's not (yet) done in the other components ...

Best,
JAN

**Comment by jkriege2** [comment]
ad 2) again ... thinking about this, maybe it's worthwile to make two versions: One with VIAs and one without (like the one you have, just the PAD renamed) ...

... and one more thing:
To remain in the LIB's convention, could you make it ETSSOP with an upper-case E and add a 1EP or _ThermalPad somewhere in the filename?

Thanks,
JAN

**Comment by jkriege2** [comment]
Thanks for the quick response ... could you also add the 1EP to the file-/footprintname?

Also the 3D model name should be the same as the footprint's name, so could you fix that? If the 3D model does not exist yet, you could simply create it by copying the matching SSOP-20 3D model and rename it accoridngly and add that into a second PR ... I can pull both then ;-)

Best,
JAN

**Comment by descampsa** [comment]
Hey JAN,

Thanks for your comments, i have fixed 1) and 3), and capitalized the name.
As for 2), i don't think the vias should belong to the footprints. You don't always put vias on the pads, and you don't always put the same number of vias.

**Comment by descampsa** [comment]
Ok, i will add the 3D model, then, if it is ok for you like that.
Do you prefer to i squash all the commits into one to have a cleaner history?

**Comment by descampsa** [comment]
Oops, actually i just noticed that the courtyard were corect, i thought i was in 0,05mm grid when i 'fixed' them, but i was in 0,1mm. 
According to KLC 6.6, the silcscreen should not be taken into account in the courtyard margin, only pads and body. I agree that silkscreen should be inside courtyard, but this was already the case, so i think courtyard was correct, and i have reverted this change.

**Pull request merged**
