### PR TITLE
added PSOP-20 package for ADA4870

### PR DESCRIPTION
**Pull request by dejfson**
Hi, this pull request is preparation for adding ADA4870 power amplifier. The package is of ssop type, but with central power pad as in JEDEC MO-166-A std. I do not provide 3D model for this (at least ..yet)

### CODE REVIEW

**Comment by evanshultz** [comment]
@dejfson 
For ease of checking, please always include the datasheet and a screenshot for any submission. Once you provide that I can review this PR. Thank you.

**Comment by evanshultz** [comment]
Also, this is the wrong lib. The lead spacing is 1.27mm which means this should go into Housings_SOIC. I just submitted an extremely similar footprint at https://github.com/KiCad/Housings_SOIC.pretty/pull/31.

**Comment by evanshultz** [comment]
@dejfson Will you be able to complete this PR?

**Comment by dejfson** [comment]
Hello evanshultz, you're right, the power package from st seems to be the same, there's hence no point to include this one. i used as well this lib, because I saw there are some 1.27mm spacing MFSOP/SOP packages. Hence from this perspective there's no need to merge.
thaaanks.
.d.

**Pull request closed without merging**
