### PR TITLE
Create MSOP-8LD-PL-1.kicad_mod

### PR DESCRIPTION
**Pull request by savenlid**
According to Micrel drawing with same name: MSOP-8LD-PL-1
alias MM8
differs quite alot from the one already here in library
3x3mm 0.65mm pitch

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
@savenlid how does this differ from **MSOP-8_3x3mm_Pitch0.65mm**?

**Comment by hackscribble** [comment]
Closing and re-opening to trigger Travis checks.

**Comment by SchrodingersGat** [comment]
@savenlid if you're still interested in contributing this, please add the `Micrel_` prefix to the footprint name and look at the KLC script outputs :)

**Comment by savenlid** [comment]
libs and footprints to be found at:
https://github.com/savenlid/kicad

**Pull request closed without merging**
