### PR TITLE
Added HTSOP-8 and SOP-8 footprint.

### PR DESCRIPTION
**Pull request by crackerizer**

### CODE REVIEW

**Comment by keruseykaryu** [comment]
HTSOP-8 and SOP-8 does not fit to this library.
This library is designed for Shrink Small Outline Packages series (SSOP, TSSOP, MSOP) which usually has lead spacing at 0.65mm or 0.5mm.

The best target for your HTSOP-8 footprint will be `Power_Packages_SMD.pretty` because it is a kind of SOIC packages with additional heat dissipation.
This repo was created a day ago so you may need to clone it with your GitHub client.

The SOP-8 is a duplicate.

Rejected. Closed.

**Comment by crackerizer** [comment]
I tried to fork Power_Packages_SMD.pretty but there is no folk option in the empty repo. Please give me a hint.

**Comment by michal777** [comment]
HTSOP-8_Pitch1.27mm.kicad_mod is duplicate of SOIC-8-1EP_3.9x4.9mm_Pitch1.27mm.kicad_mod

**Comment by CarlPoirier** [comment]
I placed an empty file in the Power_Packages_SMD.pretty repo to get it initialized so that people can fork it. Please don't care about the file name, I committed it before reading Michal's comment.

**Comment by crackerizer** [comment]
CarlPoirer: Thank you
michal777: It was my misunderstanding. The footprint is actually HTSOP-J8 which has smaller dimension than standard SOP and SOIC but larger than SSOP. Should this one still be in Power_Packages?

**Pull request closed without merging**
