### PR TITLE
Fixed a couple of KLC violations for SSOP footprints

### PR DESCRIPTION
**Pull request by SchrodingersGat**
Fixes KLC 6.4 fot TSSOP-44
Fixes KLC 10.4 for MSOP-16

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
bump

**Comment by SchrodingersGat** [comment]
@pointhi  @diggit  @ashtonchase  anyone want to check this one out? It's been here for a while now...

**Comment by SchrodingersGat** [comment]
All package outlines have now been added to the F.Fab layer

**Comment by SchrodingersGat** [comment]
Fixed pin-1 silkscreen indicator as per https://github.com/KiCad/Housings_SSOP.pretty/issues/15

**Comment by pointhi** [comment]
as said in another PR before, please add pin 1 markers on the F.Fab layer.

**Comment by CarlPoirier** [comment]
This chould be a good example:
image

Besides that, it's awesome!

**Comment by SchrodingersGat** [comment]
@CarlPoirier do you want the bevelled edge or happy with the circle?

**Comment by CarlPoirier** [comment]
I prefer the bevelled edge. It looks more streamlined to me.

**Comment by SchrodingersGat** [comment]
Ok I shall revert the most recent commit and update. We really need to be putting all these little conventions together into a more detailed document to outline requirements for "good" footprints.

**Comment by SchrodingersGat** [comment]
Any preferences between the following two examples @CarlPoirier  or @pointhi ? :)

**Option A**
a

**Option B**
b

**Comment by CarlPoirier** [comment]
I do like the first one as we still get to see the real shape!

**Comment by pointhi** [comment]
I agree with @CarlPoirier, the first one

**Comment by CarlPoirier** [comment]
Oliver, wait before proceeding. We are in discussion on the IRC channel. Join us if you wish!

**Comment by CarlPoirier** [comment]
Oliver, we're onto something. Our suggestion is to use the same pin one marker as on the actual chip.This along with the outline would become a new KLC rule and apply to all footprints. What do you think?

**Comment by SchrodingersGat** [comment]
> Our suggestion is to use the same pin one marker as on the actual chip.

So does this mean we are back to the small circle in the top-left corner? I'm happy with this or with the **Option A** as shown above. If it's the small circle option we want to go with I can un-revert the commit and all is done!

**Comment by SchrodingersGat** [comment]
Also I was not even aware of the IRC channel! Have joined now so I'll hang out there in future when I'm working on KiCad stuff

**Comment by CarlPoirier** [comment]
Yeah that would be the circle.

**Comment by SchrodingersGat** [comment]
Ok, then no work needed on this PR! LMK if you need any more changes before accepting.

**Comment by CarlPoirier** [comment]
Thank you Oliver, this is a great contribution.

**Pull request merged**
