### PR TITLE
Add TSOP-I-48 12x18.4 mm pitch 0.5 mm

### PR DESCRIPTION
**Pull request by piotr-wiszowaty**

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
Hi @piotr-wiszowaty can you please add the package shape to the F.Fab layer as per the other parts (with a 1mm bevel for pin-1 indication as per IPC)

untitled

Regards, 
Oliver

**Comment by piotr-wiszowaty** [comment]
Done.

**Comment by jkriege2** [comment]
Please also change silkscreen width to 0.12mm (update in KLCs)

Best,
JAN

**Comment by jkriege2** [comment]
Also: The pin-numbering is wrong on the rhs. It should start at the BOTTOM with 25 and end at the TOP with 48 (see DS p. 9)!

Otherwise: NICE WORK!

Best,
JAN

**Comment by piotr-wiszowaty** [comment]
Done. But check_kicad_mod.py complains about this.

**Comment by piotr-wiszowaty** [comment]
Done.

**Comment by jkriege2** [comment]
```
checking module: TSOP-I-48_12x18.4mm-Pitch0.5mm
  Violating Rule 10.1
    Footprint name must match its filename. (.kicad_mod files).
  Violating Rule 6.9
    Value and reference have a height of 1mm.
```

please ensure that you also rename the footprint name IN the file, not just the filename. Also please fix the KLC6.9 violation! 

Thanks,
JAN

**Comment by piotr-wiszowaty** [comment]
Name fixed.
The height is set to 1 mm. When I set the thickness back to
0.15 mm (without changing anything else) the 6.9 violation disappears.
So I am somewhat at a loss here.

**Comment by jkriege2** [comment]
Am 25.12.2016 um 21:37 schrieb Piotr Wiszowaty:
> Name fixed.
> The height is set to 1 mm. When I set the thickness back to
> 0.15 mm (without changing anything else) the 6.9 violation disappears.
> So I am somewhat at a loss here.

The 0.12mm were introduced into the check-script a few weeks ago ... 
maybe an update of the script helps?

**Comment by piotr-wiszowaty** [comment]
I've just merged it - check result is the same. What am I missing?
```
$ check_kicad_mod.py -v TSOP-I-48_12x18.4mm_Pitch0.5mm.kicad_mod 
checking module: TSOP-I-48_12x18.4mm_Pitch0.5mm
  Violating Rule 6.9
    Value and reference have a height of 1mm.

```
tsopi48_1mm

**Comment by jkriege2** [comment]
I think that's a bug in the script ... I tried to use the --fix option of thze script, which basically does 2 things:
2016-12-26 11_35_41-tsop-i-48_12x18 4mm_pitch0 5mm kicad_mod_ working tree - tortoisegitmerge

Only changing the linewidth was enough to cause the script to see the footprint as OK.

So I'll merge it in your form, as I think that's all correct. Could you please make a PR or add a bug to the script?

THanks,
JAN

**Pull request merged**
