### PR TITLE
Create OnSemi_Micro8.kicad_mod

### PR DESCRIPTION
**Pull request by evanshultz**
Image:
image

See https://www.onsemi.com/pub/Collateral/846A-02.PDF.

### CODE REVIEW

**Comment by jkriege2** [comment]
Hi!

maybe reduce text size for REFDES, so it fits inside?

Also you link `/TSSOP-8_3x3mm_Pitch0.65mm.wrl` as a 3D model ... is there any difference between the two packages?

Best, JAN

**Comment by evanshultz** [comment]
I saw the text thing, but I wonder how many characters need to fit? See a bit more info I wrote at https://github.com/KiCad/Housings_CSP.pretty/pull/3. Perhaps this should go into KLC 2.0?

No physical difference between the packages, just this specific footprint (really padstack size) that On Semi calls out for their parts. So I think the 3D model sharing should be OK here.

**Comment by jkriege2** [comment]
I would do the text a bit smaller ... e.g. if it's `IC25`???

Best,
JAN

**Comment by evanshultz** [comment]
Then call it `U25`! :) just kidding. I went from 1mm to 0.75mm.

**Comment by jkriege2** [comment]
Nice work!

Thanks,
JAN

**Pull request merged**
