### PR TITLE
qsop: Add QSOP-24 package footprint

### PR DESCRIPTION
**Pull request by joe-skb7**
Land pattern and outline dimensions are described in Microchip Packaging
Specification (see [1]). QSOP-16 footprint was used as a reference
(which is also relies on [1] for footprint dimensions).

The reason for adding this package is an attempt to add MAX7325AEG+
schematic symbol, which relies on this footprint.

[1] http://ww1.microchip.com/downloads/en/PackagingSpec/00000049CH.pdf

Signed-off-by: Sam Protsenko <joe.skb7@gmail.com>

### CODE REVIEW

**Comment by joe-skb7** [comment]
Regarding checker warning: please note that KLC Rev 2.0 ([here](https://github.com/SchrodingersGat/kicad-library/wiki/KLC)) says, that:

> Allowable text thickness = 0.025mm to 0.20mm (should be 10% of text size)

but the checker seems not to be aware of that, as you can see that warning:

> User-text reference label (text='%R') has a thickness of 0.08mm (expected: 0.15mm)

Looks like some collision between rules in KCL. Perhaps checker should be fixed to skip that rule, when checking `F.Fab` reference designator.

**Comment by SchrodingersGat** [comment]
@joe-skb7 the new KLC rule checker script will be a LOT better :)

This looks mostly good - just add some keyword tags! Have a look at how this is done for the similar footprints if unsure.

Otherwise OK to merge :)

**Comment by joe-skb7** [comment]
@SchrodingersGat But it already has `QSOP 0.635` tags. That's pretty much what any other footprint has. Or you mean something else?

**Comment by SchrodingersGat** [comment]
Ah ok, I was looking at another PR and got them confused. Thanks for the contribution

**Pull request merged**
