### PR TITLE
AKM SMT current sensors

### PR DESCRIPTION
**Pull request by evanshultz**
There are a several interesting AKM current sensors which have neat footprints (http://www.akm.com/akm/en/product/detail/0009/). I'm adding two of them here, and soliciting footprint naming help for the other 2 as well.

Here:
AKM_VSOP-24_7.9x5.6mm_Pitch0.65mm:
http://www.akm.com/akm/en/file/datasheet/CQ-330J.pdf
AKM_CZ-381x-10_6.5x8.1mm_Pitch0.95mm:
http://www.akm.com/akm/en/product/detail/0009/ (no public datasheet yet)

Later:
AKM_CQ-7:
http://www.akm.com/akm/en/file/datasheet/CQ-236B.pdf
AKM_CQ-7S:
http://www.akm.com/akm/en/file/datasheet/CQ-209D.pdf

Image:
image

For the other two parts, the ones that kinda look like TO-220, I have two questions:
1. What is a good footprint name? The AKM datasheets use the MPN which isn't helpful, and AKM says all four are custom packages which have no industry-standard name.
1. Where should they go? TO_SOT_Packages_[THT|SMD]? Is there a better repo for them? Maybe it's time to create a repo for current sensor footprints, like our symbol for current sensors, because they often have weird and unique footprints? The TO220-like Allegro sensors and all 4 of these AKM sensors could go there.

### CODE REVIEW

**Comment by evanshultz** [comment]
Can anyone take a look at these footprints? 2 are included in the PR here with no KLC violations and are ready to merge if the footprint names are OK. Then there are two more I'm asking about repo location and what to use for their footprint names.

**Comment by evanshultz** [comment]
@jkriege2 @poeschlr @SchrodingersGat 
Could somebody take a look at these footprints and the questions above?

**Comment by jkriege2** [comment]
- About naming: I would use MANUFACTURER_DEVICENAME as done for the CQ7
- ABout repo: A separate repo for current sensors would be a good idea, I think!
- footprints look good to me.

Best,
JAN

**Comment by poeschlr** [comment]
About repo: I would not open a new repo just for the few month until v5.
Simply commit it to the new kicad-footprint repo. (There you can make as many new libs as necessary.)

**Comment by SchrodingersGat** [comment]
Something along the lines of `CurrentSensor.pretty` would be appropriate, and yes the Allegro parts should be moved there too. Sorry that I forgot about this one.

**Comment by evanshultz** [comment]
New PR submitted at https://github.com/KiCad/kicad-footprints/pull/12. I'll close this PR now.

**Pull request closed without merging**
