### PR TITLE
added TSSOP-28 variant with thermal pad

### PR DESCRIPTION
**Pull request by jkriege2**
- see http://www.ti.com/lit/ds/symlink/tlc5940.pdf
- there are still two KLC issues:
  1. the 3D model is the same as for the footprint without thermal pad ... so I don't see why I should copy the 3D model
  2. I still get the following violation, which I don't understand:
    "Violating Rule 10.5: Attributes is set to the appropriate value, see tooltip for more information."

htssop28

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
**10.5** means that you need to set the "INSERT" attribute for the part.
As this is a surface mount part, this attribute needs to be set so that when you generate a .pos file (for a pick-and-place machine), the part gets included in that file.

untitled

**Comment by jkriege2** [comment]
Hhmmm ... In the Footprint-Editor that is set ... ??? 
For the component TSSOP-28_4.4x9.7mm_Pitch0.65mm.kicad_mod which I copied to create the HTSSOP I don't get that error ... I'm a bit confused. Any ideas? Is the script/KiCAD confused as there are SMD and TH pads?

Best,
JAN

**Comment by SchrodingersGat** [comment]
Ah, yep good point. The script is most likely wanting to set the INSERT attribute to both TRUE and FALSE due to the different pad types. 

The script should be updated to accommodate this I think!

**Comment by jkriege2** [comment]
so, can you merge this, or is something still missing?

**Comment by SchrodingersGat** [comment]
I would suggest adding a suffix "_ThermalPad" to this part, for easier differentiation.

**Comment by jkriege2** [comment]
done!

**Comment by jkriege2** [comment]
thanks! :+1: :-)

**Pull request merged**
