### PR TITLE
Corrected SSOP20 (SOT226) package.

### PR DESCRIPTION
**Pull request by greenscreenflicker**
SSOP20 package with body above is not correct. Corrected it for SSOP20, other SSOP packages might have this issue too.
Also added a reflow version with rounded pads.

### CODE REVIEW

**Comment by greenscreenflicker** [comment]
@wiebus @SchrodingersGat Can you please check this pull request?

**Comment by SchrodingersGat** [comment]
@greenscreenflicker what was wrong with the old footprint?

**Comment by greenscreenflicker** [comment]
Old version has too small outline. SSOP needs some space above and below. The current footprint is TSSOP style without spaces,

**Comment by hackscribble** [comment]
Hi @greenscreenflicker 

Sorry your pull request got forgotten for so long. 

Since you submitted it, there have been changes to the footprints in `Housings_SSOP.pretty`.  The current version of `SSOP-20_4.4x6.5mm_Pitch0.65mm.kicad_mod` looks like this ...

image

The body size is 4.4mm x 6.5mm, which matches this datasheet from NXP http://www.nxp.com/docs/en/package-information/SOT266-1.pdf, and the courtyard is 7.1mm tall, which is close to the value in the datasheet (7.3mm).

(Based on the files in the PR, I've assumed it **was** the SOT266 that you meant, and that "SOT226" in the PR title was a typo).

If this does not fix the problem you saw, and you are still interested in contributing, please open a new pull request (in synch with the current master branch) and check your contribution against the latest KiCad Library Convention here: https://github.com/KiCad/kicad-library/wiki/Kicad-Library-Convention.

Many thanks.

**Pull request closed without merging**
