### PR TITLE
added ST MultiPowerSO-30

### PR DESCRIPTION
**Pull request by jkriege2**
required by this PR: https://github.com/KiCad/kicad-library/pull/1206

http://www.st.com/content/ccc/resource/technical/document/datasheet/group2/66/b8/f5/2c/9a/66/41/c7/CD00043711/files/CD00043711.pdf/jcr:content/translations/en.CD00043711.pdf

2017-05-03 08_16_29-footprint editor no active library

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
Jan,

This looks good, I would suggest dropping the `3-EP_16.0x17.2mm_Pitch1mm` as it is a vendor specific footprint and can be described just using the vendor name...

**Comment by jkriege2** [comment]
OK, I renamed it ... and added a silkscreen drawing, which I forgot before ;-)

2017-05-04 07_46_49-footprint editor no active library

**Comment by jkriege2** [comment]
@SchrodingersGat Can this be merged?

Best,
JAN

**Comment by SchrodingersGat** [comment]
Thanks for the contribution Jan :)

**Pull request merged**
