### PR TITLE
added HTSSOP-20 package

### PR DESCRIPTION
**Pull request by jkriege2**
2017-01-21 21_47_30-footprint editor no active library

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
Jan one of the thermal pad pins is labeled "24" (should be "21"

**Comment by SchrodingersGat** [comment]
Also can you add a version without the "Thermal_Pads" (e.g. no vias)?

**Comment by jkriege2** [comment]
fixed. I think the packages you mean are 
- `ETSSOP-20-1EP_4.4x6.5mm_Pitch0.65mm`
- `TSSOP-20_4.4x6.5mm_Pitch0.65mm`

best,
JAN

best,
JAN

**Comment by SchrodingersGat** [comment]
Ah, of course. I was blind!

Thanks for the contribution.

**Pull request merged**
