### PR TITLE
Add TSOP-I footprints

### PR DESCRIPTION
**Pull request by evanshultz**
Merging footprints from SMD_Packages as mentioned at https://github.com/KiCad/SMD_Packages.pretty/issues/20.

Datasheets:
http://www.fujitsu.com/downloads/MICRO/fma/pdfmcu/f32pm25.pdf
https://www.micron.com/~/media/documents/products/technical-note/nor-flash/tn1225_land_pad_design.pdf

Note: There is already a TSOP-I-48 footprint here, but it uses extremely long pads that go under the part body. This is ill-advised since it can allow solder to flow under the part and push it up, preventing proper soldering. Also, the body dimensions on that part are YxX instead of the normal XxY. I'll delete that footprint as part of this PR if requested.

Image:
image

### CODE REVIEW

**Comment by evanshultz** [comment]
@jkriege2 And this one? Please read the note above.

**Comment by jkriege2** [comment]
Yes, please delete the old one ... also I made a PR to fix the one part that uses that old package (and renames the 3D model): https://github.com/KiCad/kicad-library/pull/1549
please merge that, when I merge this!

Otherwise this looks fine and I would merge it!

JAN

**Comment by evanshultz** [comment]
@jkriege2 Thanks! Your PR looks good and is merged.

**Comment by jkriege2** [comment]
Hi could you please delete the old TSOP-I still in this PR? Then I'll merge.
JAN

**Comment by evanshultz** [comment]
@jkriege2 My mistake. Forgot about that part. Old footprint is now deleted.

**Comment by jkriege2** [comment]
Great!

Thanks,
JAN

**Pull request merged**
