### PR TITLE
Add SOP-16_4.4x10.4

### PR DESCRIPTION
**Pull request by svheymann**

### CODE REVIEW

**Comment by jkriege2** [comment]
Hi!

lokks mostly good to me. One minor thing: The courtyard offset is not correct. it should be 0.25mm from the pad-outsides or the package outline. In your footprints it's 0.25mm from the pads and 0.3mm from the package outline (F.Fab).

If you want to play test pilot, you can clone this PR: https://github.com/KiCad/kicad-library-utils , delete the courtyard and run the script with `--fix` on the footprint. then it should create the correct courtyard for you!

best,
JAN

**Comment by svheymann** [comment]
I did that, the file has been changed, but the courtyard line has not been added to the file:

check_kicad_mod.py --fix -v Housings_SSOP.pretty\SOP-16_4.4x10.4mm_Pitch1.27mm.kicad_mod
checking module: SOP-16_4.4x10.4mm_Pitch1.27mm
  Violating Rule 6.6
    Courtyard line has a width 0.05mm. This line is placed so that its clearance is measured from its
    center to the edges of pads and body, and its position is rounded on a grid of 0.01mm.
      No courtyard line was found at all.

    No courtyard line found in the module
Please, resave the files using KiCad to keep indentation standard.

Did i miss something?

**Comment by jkriege2** [comment]
no, sorry my mistake, I posted the wron link. You need this PR:
https://github.com/KiCad/kicad-library-utils/pull/77

It's not yet in the trunk

Best,
JAN

**Comment by svheymann** [comment]
I used git remote add  and merged the commits from the PR. But now i get a TypeError:

Traceback (most recent call last):
  File "....\GitHub\kicad-library-utils\pcb\check_kicad_mod.py", line 76, in <module>
    rule.fix()
  File "....\GitHub\kicad-library-utils\pcb\rules\rule6_6.py", line 128, in fix
    if re.match("BGA\-.*", module.name) or re.match(".*Housing.*BGA.*", self.module_dir):
  File "C:\Python34\lib\re.py", line 160, in match
    return _compile(pattern, flags).match(string)
TypeError: expected string or buffer

Maybe i need more than just that PR? Should i use your fork?

**Comment by jkriege2** [comment]
Oh, that's a bug ... I fixed it, just get the new version and try again!

JAN

**Comment by svheymann** [comment]
worked! Actually... thats quite cool :)

**Pull request merged**
