### PR TITLE
Add ST_PowerSSO-24, fix ST_MultiPowerSO-30

### PR DESCRIPTION
**Pull request by evanshultz**
This is the last footprint required when overhauling the audio library (https://github.com/KiCad/kicad-library/pull/1560). Yay!

See my comments about naming a similar package at https://github.com/KiCad/Housings_SOIC.pretty/pull/31. I used a vendor prefix here because I don't see a JEDEC number or other vendors using this package, whereas I do on the linked footprint. So this one may actually be vendor-specific. But adding overall body size or some other additional info would be reasonable to me.

Docs:
- http://www.st.com/content/ccc/resource/technical/document/datasheet/01/3e/00/03/cd/f5/4f/e7/CD00022675.pdf/files/CD00022675.pdf/jcr:content/translations/en.CD00022675.pdf
- http://www.st.com/content/ccc/resource/technical/document/datasheet/48/5f/ca/52/bb/3a/45/a7/DM00043932.pdf/files/DM00043932.pdf/jcr:content/translations/en.DM00043932.pdf

Image:
image

While I was in there, I realized the 3D model file extension was wrong for another ST part, so I fixed it. And gave it a shorter URL.

### CODE REVIEW

**Comment by jkriege2** [comment]
looks good ... would you be willing to add a version with heat-trasnfer vias and a bottom-pad? see VNI4140K-32 suggested footprint.

cu
JAN

**Comment by evanshultz** [comment]
I added the ST PowerSO-36 footprints, adding them here since the lead pitch is 0.65mm. I agree it is a bit arbitrary between SOIC and SSOP repos and perhaps there's a better way to organize besides lead pitch. Anyway, here is the image:
image

Dimensions differed between two PowerSO-36 datasheets I saw and the app note, so I copied the dimensions mostly from the PowerSO-20 where I could since a nice and full footprint was given for it in the app note.

I also spotted another small mistake in ST_MultiPowerSO-30 and fixed it; F.Fab lines were 0.12mm wide.

I will make a thermal via version of PowerSSO-24 footprint next. Since I don't see a JEDEC or JEITA reference for this package, I'll keep the footprint name as ST-specific.

**Comment by evanshultz** [comment]
I found http://freedatasheets.com/downloads/Technical%20Note%20Powersso24%20TN0054.pdf, which mentions that JEDEC MO-271 covers the PowerSSO family. However, I don't see this doc on ST's website. The JEDEC spec can be found at http://cad-design.ru/downloads/jedec_mo-271a/d/mo-271a.pdf.

The JEDEC spec calls the packages `PDSO /SOIC, SOP`, but also mentions that ST has a patent on this package. So ST-specific does seem like the right way to go.

Amkor may make the actual package, as can be seen at https://www.amkor.com/go/epad-tssop-datasheet.

**Comment by evanshultz** [comment]
Note that there is a lot of related info at https://github.com/KiCad/Housings_SOIC.pretty/pull/31.

Updated and new PowerSSO-24 footprints:
image

Would you like me to do the PowerSSO-36 footprints as well? The difference between it and the PowerSO-36, at least from what I can find, is all on the outside. The PowerSO has a big slug inside the body while PowerSSO is a smaller, squarish thermal pad.

**Comment by jkriege2** [comment]
Since you're at it: Go ahead for the PowerSSO-36 ;-)

**Comment by evanshultz** [comment]
@jkriege2 I added bottom thermal pads on the existing parts, and the PowerSSO-36 footprints. Please check, and thank you!
image
image

**Comment by evanshultz** [comment]
@jkriege2 Jan?

**Comment by jkriege2** [comment]
great work!
JAN

**Pull request merged**
