### PR TITLE
Added TSSOP-44 package

### PR DESCRIPTION
**Pull request by SchrodingersGat**
Added footprint for TSSOP-44 package

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
Added footprints for TSSOP-44

Added 6x configurations for MSOP-16 package

**Comment by CarlPoirier** [comment]
Hi Oliver,

These are great footprints. The only thing to correct is the 160th pad of the MSOP-16-1EP-VIA.

**Comment by SchrodingersGat** [comment]
Renamed 160 -> 16
Also renamed 10 -> 16 on another MSOP-16 which was slightly wrong.

**Comment by CarlPoirier** [comment]
Thanks!

**Pull request merged**
