### PR TITLE
Add SSOP-28_3.9x10.0mm_Pitch0.635.kicad_mod

### PR DESCRIPTION
**Pull request by frejanordsiek**
Ran into an unusual SSOP-28 with 0.635 mm pin spacing instead of the usual 0.650 mm, so I just took SSOP-24_3.9x8.7mm_Pitch0.635.kicad_mod and moved the whole thing upwards 0.635 mm and extended the bottom back down 1.27 mm and added the extra pads.

### CODE REVIEW

**Comment by frejanordsiek** [comment]
Found a small issue in my pull request, namely that the name in the file (first line) has an extra ``Housings_SSOP:`` in front of it. I am not sure how to fix this in the PR itself other than submit a new one.

**Comment by poeschlr** [comment]
If you push to the same branch as your original source branch, the pull request gets updated automatically.

**Comment by frejanordsiek** [comment]
There, got the various issues fixed. Only item really missing is that there is no 3D model yet, but that is a different repo (KiCad/kicad-library)

**Comment by poeschlr** [comment]
3d models for these sort of footprint are script generated.
https://github.com/easyw/kicad-3d-models-in-freecad/tree/master/cadquery/FCAD_script_generator/GW_QFP_SOIC_SSOP_TSSOP_SOT

maybe @Shackmeister is motivated to generate the required model.

The models would go into the kicad-library repo as you already guessed. And they should go into the new [packages3d](https://github.com/KiCad/packages3D) repo as well. (3d models are not required for the pull request to be accepted.)

---

Do you have a datasheet where this package is described? (Would make it possible to review the footprint in detail. The link to the datasheet should also be added to the description.)

For now it seems the outline on fab might not be quite correct. (not symmetrical in y direction) The fab outline should exactly represent the nominal body size.

The courtyard clearance is also not quite right in y direction. (should be 0.25mm from center of fab line to center of courtyard line in y direction and 0.25 from edge of pad to center of courtyard line.)

The fab outline should have a width of 0.1mm and the silk outline should have a width of 0.12mm

**Comment by frejanordsiek** [comment]
I will try to fix those things.

As far as the not being symmetrical in the y-direction, I think that happened when I slid it downward by 0.005 mm so that it was 0.01 mm aligned (was symmetric before that since I just moved the lines of the 24 pin version one by 0.635 mm up and down to accommodate the four extra pins). I really should have moved the top end up 0.005 mm and the bottom end down 0.005 mm (best to show a larger size than a smaller one).

The courtyard line is the outer grey outline and the fab line is the yellow outline, correct?

As for the datasheet, there wasn't a specific one for the package by itself. Just the datasheet for the device which had the package. It was an IDT ICS674-01, whose datasheet is at https://www.idt.com/document/dst/674-01-datasheet

**Comment by poeschlr** [comment]
According to the datasheet the nominal size for this package might be 3.9x9.9mm. (average between max and min dimension)
This should be reflected by the part name and the fab outline.

> The courtyard line is the outer grey outline and the fab line is the yellow outline, correct?

The color depends on your kicad settings.
I think by default for fab is yellow. And CrtYd (courtyard) might be gray by default.
You can easily check this in the layer tab. (Right side of the footprint editor)
screenshot from 2017-08-16 14-34-53

**Comment by SchrodingersGat** [comment]
@frejanordsiek 



In preparation for the v5 KiCad software release, we are marking this repository as "legacy" and not accepting any new pull requests. These footprints have been moved to the new `kicad-footprints` repository at https://github.com/kicad/kicad-footprints

Sorry for the inconvenience, however this change will make the contribution process easier for everyone.

Please resubmit your contribution over at the new repository :)

**Pull request closed without merging**
