### PR TITLE
adding SSOP-8 & VSSOP-8

### PR DESCRIPTION
**Pull request by jeromebeguin**

### CODE REVIEW

**Comment by jkriege2** [comment]
Hi!

**VSSOP-8:** courtyard is too close (should be 0.25mm offset) and add keywords+description, set placement to SMD, rotate 90° clockwise
2017-02-08 20_12_04-footprint editor no active library

**SSOP-8**: as above

JAN

**Comment by jeromebeguin** [comment]
I don't really know what description & keyword using. All information are include in the name.

**Comment by jkriege2** [comment]
names are usually short form. In doc and keywords you can give longer, searchable descriptions, e.g. write "Ball grid array" for a BGA, or add a datasheet-link to the description.
JAN

**Comment by jkriege2** [comment]
please fix these:

```
D:\KiCAD\kicad-library-utils\pcb>check_kicad_mod.py d:\KiCAD\review.pretty\Housings_SSOP.pretty\SSOP-8_2.95x2.8mm_Pitch0.65mm.kicad_mod -v
checking module: SSOP-8_2.95x2.8mm_Pitch0.65mm
  Violating Rule 10.7
    All other properties are left to default values. (Move and Place: Free; Auto Place: 0 and 0,  Local
    Clearance Values: 0)
      Attribute solder_mask_margin == 0.07 != 0!


D:\KiCAD\kicad-library-utils\pcb>check_kicad_mod.py d:\KiCAD\review.pretty\Housings_SSOP.pretty\VSSOP-8_2.3x2mm_Pitch0.5mm.kicad_mod -v
checking module: VSSOP-8_2.3x2mm_Pitch0.5mm
  Violating Rule 10.2
    Doc property contains a full description of footprint.
      Documentation was empty!

  Violating Rule 10.6
    Attributes is set to the appropriate value, see tooltip for more information.
      There are mode SMD-pads (8) than THT-pads (0), but the attribute is not set to 'smd', but 'pth'.
  Violating Rule 10.7
    All other properties are left to default values. (Move and Place: Free; Auto Place: 0 and 0,  Local
    Clearance Values: 0)
      Attribute solder_mask_margin == 0.05 != 0!
```

You can use these scripts to check the KLC rules (at least some of them) and even fix them with `--fix`. In any case, please use the `-v` option to get verbose error info (otherwise it will only give you KLC numbers 3.2 ).
   https://github.com/KiCad/kicad-library-utils/tree/master/pcb

Best,
JAN

**Comment by jkriege2** [comment]
nice work!

One final thing: There is already a VSSOP-8 in the lib, which is only slightly larger (0.1mm) but has essentially the same pins:
2017-02-10 21_43_24-pcbnew d__kicad_kicad-library-review-project_kicad-library-review kicad_pcb
Is there any advantage in yours? the size difference seems to be due to size ranges in DS?

thanks,
JAN

**Comment by jeromebeguin** [comment]
I have no idea. I just followed the datasheet. But having both of them could maybe help for footprint matching non ?

**Comment by jkriege2** [comment]
OK, I will merge!

Thanks for the work!
JAN

**Pull request merged**
