### PR TITLE
preparation for new 3d models

### PR DESCRIPTION
**Pull request by Shackmeister**

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
@Shackmeister please notify me when the 3D models are ready to merge. I don't want to merge this PR until that is the case otherwise users will have broken 3D models in the interim.

Thanks

**Comment by SchrodingersGat** [comment]
Also please add "%R" on all the footprints you have touched and bring them up to KLC2.0

**Comment by Shackmeister** [comment]
@SchrodingersGat pretty sure I'm only adding 3d settings/paths (except for one where I'm changing the the offset on one axis from 0.02 to 0)
Not sure what you mean by adding %R

**Comment by SchrodingersGat** [comment]
If that's the case then it should be ok to merge.

The Travis scripts show you where the errors are. The SSOP footprints are violating [KLC 7.4](https://github.com/KiCad/kicad-library/wiki/Kicad-Library-Convention) as they do not have a second RefDes on the F.Fab layer.

**Comment by Shackmeister** [comment]
@SchrodingersGat that is the case.
should ${KISYS3DMOD}/ be added to the 3d path?

**Comment by SchrodingersGat** [comment]
@Shackmeister are you using nightly or stable build? I am interested to know if the ${KISYS3DMOD} prefix causes any issue with stable build.

**Comment by Shackmeister** [comment]
Im running stable and ${KISYS3DMOD} seems to work fine

I noticed the footprints having paranthesis in the name needs "" around the 3d path.. I guess paranthesis doesnt comply with KLC

**Comment by Shackmeister** [comment]
can you explain how and where the %R should be added? then Ill fix it

and how should the MSOP-16(12)-1EP_3x4mm_Pitch0.5mm etc be renamed?

**Comment by SchrodingersGat** [comment]
## %R

This is a second copy of the RefDes that needs to go on the `F.Fab` layer at the center of the footprint (location 0,0, generally). To add this, place a text item at this location with the text value `%R`.

## MSOP-16(12)

IPC-7351C has a provision for footprints (land patterns) that have missing pins:

It should be named `MSOP-12-16_` where `12` is the number of used pins and `16` is the total pin count (including skipped pins).

Does this make sense?

**Comment by Shackmeister** [comment]
@SchrodingersGat 
I think thats about it from my side :)
perhaps you consider to let Travis remove "-VIA" and "_Handsoldering" from the filename when comparing the 3d model path and filename (if it doesnt comply in first try)

**Comment by Shackmeister** [comment]
skaermbillede fra 2017-04-11 11-39-34

**Comment by SchrodingersGat** [comment]
Thanks for your work :)

**Pull request merged**
