### PR TITLE
Added HTSSOP-16-1EP_4.4x5mm_Pitch0.65mm

### PR DESCRIPTION
**Pull request by Lichtso**
For DRV8833PWP see: https://github.com/KiCad/kicad-library/pull/1605

### CODE REVIEW

**Comment by Lichtso** [comment]
htssop-16-1ep_4 4x5mm_pitch0 65mm

**Comment by SchrodingersGat** [comment]
Hi @Lichtso thanks for contributing. Same points as for your other PR

1. The footprint file must have `.kicad_mod` extension
1. Please add two versions of this footprint:
   1. One with the thermal vias and has the `_ThermalVias` suffix
   1. One without any thermal vias

Thanks

**Comment by SchrodingersGat** [comment]
Just a couple of changes needed :

1. Add a text item at (0,0) on the `F.Fab` layer that says `%R` - this will make a second RefDes item
1. Increase the pad size of the thermal vias so the annular ring is at least 0.15mm

**Comment by SchrodingersGat** [comment]
Thanks for your contributions :)

**Pull request merged**
