### PR TITLE
Added QSOP-20_3.9x8.6mm_Pitch0.64mm to the library

### PR DESCRIPTION
**Pull request by yo3iti**
Mainly to support with footprint the ADuM7643.

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
@yo3iti this looks great, fine work :)

Just a couple of small suggestions:

1. Add extra RefDes to F.Fab layer (use text "%R" to add this) as shown below
1. Move RefDes on Silk layer and also fp name closer to the part
1. Adjust silkscreen around the component body as shown
1. Change F.Fab lines to 0.1mm (see output of the checks on this PR)
1. Ignore the courtyard error, the courtyard looks fine.
1. Vertically-center the part (it is not centered on the x-axis)
1. The datasheet is strange. Pin spacing says 0.635mm but pad spacing is 0.64mm?

asfasdf

**Comment by poeschlr** [comment]
@yo3iti Would you care to answer the questions posted by oliver?

**Comment by evanshultz** [comment]
The pad spacing should be 0.635mm. See the note below the drawing essentially saying the millimeter dimensions are useless. 0.025" is exactly 0.635mm. I checked with ADI to confirm the stupidity on their part.

Here is the info I could find:
- [Datasheet](http://www.analog.com/media/en/technical-documentation/data-sheets/ADuM7640_7641_7642_7643.pdf)
- [Package drawing](http://www.analog.com/media/en/package-pcb-resources/package/184195322rq_20.pdf)
- [Footprint for Ultra Librarian](http://www.analog.com/en/design-center/packaging-quality-symbols-footprints/symbols-and-footprints/ADuM7643.html)
- Much better-looking datasheets with this package from [Fairchild](https://www.fairchildsemi.com/package-drawings/MQ/MQA20.pdf), [Vishay](http://www.vishay.com/docs/60002/osop.pdf), [Pericom](https://www.diodes.com/assets/Datasheets/PI49FCT32807.pdf)

@yo3iti If I don't hear from you in the next 2 days I'll consider you've abandoned this PR and will close it.

**Comment by evanshultz** [comment]
Closing due to lack of response from originator and better PR for this footprint at https://github.com/KiCad/Housings_SSOP.pretty/pull/36.

**Pull request closed without merging**
