### PR TITLE
Add TSSOP-28-1EP_4.4x9.7mm_Pitch0.65mm.kicad_mod

### PR DESCRIPTION
**Pull request by rdeterre**
Adds a thermal pad to the TSSOP-28 footprint based on [the TPA3312D1 datasheet](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=2&cad=rja&uact=8&ved=0CCUQFjABahUKEwj9tvKkpKrIAhXDax4KHY8KBB0&url=http%3A%2F%2Fwww.ti.com%2Flit%2Fds%2Fsymlink%2Ftpa3112d1.pdf&usg=AFQjCNGCV2RWimsuIGspg5PLYE1e8f6Y1g&sig2=8YO72rx1k70uMipiRSPfsQ). 

I haven't been able to reproduce the recommended pad where the solder mask extends inwards (see datasheet p. 26)

Thanks

### CODE REVIEW

**Comment by pointhi** [comment]
Please apply KLC:

```
checking module: TSSOP-28-1EP_4.4x9.7mm_Pitch0.65mm
  Violating Rule 10.4
    Value is filled with footprint name and is placed on the fabrication layer.
  Violating Rule 10.7
    3D Shape ".wrl" files are named the same as their footprint and are placed in a folder named the
    same as the footprint library replacing the ".pretty" with ".3dshapes".
```

for 10.7, I don't know yet about reusing exisiting symbols without cloning (which would make sense).

@CarlPoirier, @ricardocrudo what's your normal workflow about 10.7? Simply cloning the package in the repo with the name (and only .wrl or also the .wings file?)

**Comment by rdeterre** [comment]
Thanks for the feedback. I've made the changes according to KLC. Should I make a PR on `kicad-library` to add the 3D model or is it possible to add it here as well?

**Comment by pointhi** [comment]
Please look onto other 1EP footprints how they made the center pad

**Comment by hackscribble** [comment]
Closing and re-opening to trigger Travis checks.

**Comment by hackscribble** [comment]
Hi @rdeterre   Sorry for the delay in getting back to review this again.

There are some KLC errors that need to be addressed: https://travis-ci.org/KiCad/Housings_SSOP.pretty/builds/249590579?utm_source=github_status&utm_medium=notification

Latest version of KLC is here: https://github.com/KiCad/kicad-library/wiki/Kicad-Library-Convention

> Should I make a PR on kicad-library to add the 3D model or is it possible to add it here as well?

If I understand correctly, your footprint matches an existing footprint and 3D model apart from the addition of the exposed pad?  In that case, I suggest you use the name of the **existing** 3D model in your footprint, rather than raising a PR to clone the existing model.

**Comment by evanshultz** [comment]
@rdeterre Thanks for making a first-time contribution to KiCad. There are a number of items above that need to be addressed, both to correct the footprint and to changes for footprint requirements. Please respond if you're willing to make the necessary changes so this footprint can be merged. Thanks!

**Comment by rdeterre** [comment]
Hello everyone. Sorry for the delay, I'll look at getting these changes done before the end of the week :)

**Comment by rdeterre** [comment]
Hello all. I updated the footprint by copying from the current state of TSSOP-28_4.4x9.7mm_Pitch0.65mm.kicad_mod. The only issue now is that if I re-use the name of the non-EP footpring for the 3D model, KLC complains about rule 10.4. What should I do about that?

**Comment by evanshultz** [comment]
@rdeterre That's fine. We do use common 3D models in these situations. This is one place where case-by-case we accept violations because most of the time the rules checker will find a real issue.

Sorry that I'm not able to review this right now, but perhaps someone else can or I can do it later. Thanks!

**Comment by SchrodingersGat** [comment]
@rdeterre the 3D model violation is fine in this case as mentioned above. The footprint otherwise looks great, so I'm happy to merge. Thanks for your contribution.

**Pull request merged**
